## 빅데이터 비즈니스 관점
- 데이터 많은 회사가 결국 이깁니다. 
- 데이터를 활용!
  + OPENAPI 형태로 돈을 제공
- API 제공하는 회사는 굉장히 많음
  + 빅테크 기업들은 거의 다 제공 중

In [3]:
import requests

url = "http://data.ex.co.kr/openapi/trtm/realUnitTrtm?key=1308370912&type=json&iStartUnitCode=101&iEndUnitCode=103&numOfRows=100&pageNo=1"
req = requests.get(url)
print(req)

<Response [200]>

- json 형태로 출력

In [4]:
json_result = req.json()
json_result

{'count': 805,
 'pageNo': 1,
 'numOfRows': 99,
 'pageSize': 9,
 'realUnitTrtmVO': [{'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.433333333333334',
   'timeMax': '13.400',
   'timeMin': '10.316',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:10',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '59',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.333333333333334',
   'timeMax': '14.700',
   'timeMin': '9.966',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:15',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '223',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.783333333333333',
   'timeMax': '13.533',
   'timeMin': '10.700',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:20',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '55',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.783333333333333',
   'timeMax': '12.666',
   'timeMin': '9.966',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:25',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '54',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.558333333333334',
   'timeMax': '14.066',
   'timeMin': '9.016',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:30',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '190',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.883333333333333',
   'timeMax': '13.033',
   'timeMin': '9.016',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:35',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '47',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.95',
   'timeMax': '13.133',
   'timeMin': '10.333',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:40',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '53',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.925',
   'timeMax': '15.350',
   'timeMin': '8.866',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:45',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '191',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.533333333333333',
   'timeMax': '15.350',
   'timeMin': '8.866',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:50',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '59',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.566666666666666',
   'timeMax': '13.716',
   'timeMin': '11.250',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '10:55',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '50',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '9.3',
   'timeMax': '45.433',
   'timeMin': '8.116',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11  ',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '554',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.916666666666666',
   'timeMax': '45.433',
   'timeMin': '10.216',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:00',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '160',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.033333333333333',
   'timeMax': '12.116',
   'timeMin': '10.216',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:05',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '40',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.783333333333333',
   'timeMax': '12.166',
   'timeMin': '10.266',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:10',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '38',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.616666666666667',
   'timeMax': '14.266',
   'timeMin': '8.116',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:15',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '190',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.8',
   'timeMax': '12.883',
   'timeMin': '10.766',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:20',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '51',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.683333333333334',
   'timeMax': '13.950',
   'timeMin': '8.550',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:25',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '47',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.583333333333334',
   'timeMax': '14.083',
   'timeMin': '9.550',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:30',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '204',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.633333333333333',
   'timeMax': '14.083',
   'timeMin': '9.550',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:35',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '60',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.583333333333334',
   'timeMax': '13.000',
   'timeMin': '9.900',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:40',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '44',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.466666666666667',
   'timeMax': '13.516',
   'timeMin': '9.733',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:45',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '176',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.433333333333334',
   'timeMax': '13.516',
   'timeMin': '9.933',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:50',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '51',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.35',
   'timeMax': '13.200',
   'timeMin': '9.733',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '11:55',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '47',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '9.616666666666667',
   'timeMax': '19.950',
   'timeMin': '8.283',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12  ',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '415',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.633333333333333',
   'timeMax': '16.033',
   'timeMin': '9.550',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:00',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '131',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '11.616666666666667',
   'timeMax': '13.550',
   'timeMin': '9.550',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:05',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '30',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.066666666666666',
   'timeMax': '16.033',
   'timeMin': '11.383',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:10',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '29',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.625',
   'timeMax': '19.950',
   'timeMin': '8.283',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:15',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '117',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '13.383333333333333',
   'timeMax': '19.950',
   'timeMin': '8.283',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:20',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '34',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '13.416666666666666',
   'timeMax': '15.716',
   'timeMin': '11.216',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:25',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '25',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.883333333333333',
   'timeMax': '17.183',
   'timeMin': '8.350',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:30',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '172',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '13.0',
   'timeMax': '17.183',
   'timeMin': '10.583',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:35',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '55',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.466666666666667',
   'timeMax': '13.883',
   'timeMin': '9.350',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:40',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',
   'tcsCarTypeCode': '1',
   'tcsCarTypeDivName': '소형차',
   'tcsCarTypeDivCode': '1',
   'efcvTrfl': '33',
   'iStartEndStdTypeCode': None},
  {'pageNo': None,
   'numOfRows': None,
   'startUnitCode': '101 ',
   'endUnitCode': '103 ',
   'stdDate': '20230110',
   'sumTmUnitTypeCode': None,
   'startEndStdTypeCode': '2',
   'timeAvg': '12.016666666666667',
   'timeMax': '13.766',
   'timeMin': '9.333',
   'iStartUnitCode': None,
   'iEndUnitCode': None,
   'stdTime': '12:45',
   'startUnitNm': '서울',
   'endUnitNm': '수원신갈',
   'startEndStdTypeNm': '도착기준통행시간',
   'tcsCarTypeName': '1종',

- 데이터 가공

In [9]:
cars = json_result['realUnitTrtmVO']
# len(cars)
records = []
for car in cars:
  dic = {}
  dic['date'] = car['stdDate']
  dic['carType'] = car['tcsCarTypeDivName']
  dic['time'] = car['stdTime']
  dic['timeAvg'] = car['timeAvg']
  records.append(dic)

records

[{'date': '20230110',
  'carType': '소형차',
  'time': '10:10',
  'timeAvg': '11.433333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:15',
  'timeAvg': '11.333333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:20',
  'timeAvg': '11.783333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:25',
  'timeAvg': '11.783333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:30',
  'timeAvg': '11.558333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:35',
  'timeAvg': '11.883333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '10:40', 'timeAvg': '11.95'},
 {'date': '20230110', 'carType': '소형차', 'time': '10:45', 'timeAvg': '11.925'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:50',
  'timeAvg': '12.533333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '10:55',
  'timeAvg': '12.566666666666666'},
 {'date': '20230110', 'carType': '소형차', 'time': '11  ', 'timeAvg': '9.3'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:00',
  'timeAvg': '11.916666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:05',
  'timeAvg': '12.033333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:10',
  'timeAvg': '11.783333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:15',
  'timeAvg': '11.616666666666667'},
 {'date': '20230110', 'carType': '소형차', 'time': '11:20', 'timeAvg': '11.8'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:25',
  'timeAvg': '11.683333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:30',
  'timeAvg': '11.583333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:35',
  'timeAvg': '11.633333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:40',
  'timeAvg': '11.583333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:45',
  'timeAvg': '11.466666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '11:50',
  'timeAvg': '11.433333333333334'},
 {'date': '20230110', 'carType': '소형차', 'time': '11:55', 'timeAvg': '11.35'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12  ',
  'timeAvg': '9.616666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:00',
  'timeAvg': '11.633333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:05',
  'timeAvg': '11.616666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:10',
  'timeAvg': '12.066666666666666'},
 {'date': '20230110', 'carType': '소형차', 'time': '12:15', 'timeAvg': '12.625'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:20',
  'timeAvg': '13.383333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:25',
  'timeAvg': '13.416666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:30',
  'timeAvg': '12.883333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '12:35', 'timeAvg': '13.0'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:40',
  'timeAvg': '12.466666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:45',
  'timeAvg': '12.016666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '12:50',
  'timeAvg': '11.716666666666667'},
 {'date': '20230110', 'carType': '소형차', 'time': '12:55', 'timeAvg': '11.5'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '00  ',
  'timeAvg': '7.583333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '00:00', 'timeAvg': '7.85'},
 {'date': '20230110', 'carType': '소형차', 'time': '00:05', 'timeAvg': '7.85'},
 {'date': '20230110', 'carType': '소형차', 'time': '00:10', 'timeAvg': '7.8'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '00:15',
  'timeAvg': '7.683333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '05:15',
  'timeAvg': '8.066666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '05:20',
  'timeAvg': '8.166666666666666'},
 {'date': '20230110', 'carType': '소형차', 'time': '05:25', 'timeAvg': '8.15'},
 {'date': '20230110', 'carType': '소형차', 'time': '05:30', 'timeAvg': '8.125'},
 {'date': '20230110', 'carType': '소형차', 'time': '05:35', 'timeAvg': '8.1'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '05:40',
  'timeAvg': '8.183333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '05:45',
  'timeAvg': '8.241666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '05:50',
  'timeAvg': '8.333333333333334'},
 {'date': '20230110', 'carType': '소형차', 'time': '05:55', 'timeAvg': '8.45'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06  ',
  'timeAvg': '8.166666666666666'},
 {'date': '20230110', 'carType': '소형차', 'time': '06:00', 'timeAvg': '8.325'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:05',
  'timeAvg': '8.383333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:10',
  'timeAvg': '8.583333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:15',
  'timeAvg': '8.683333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:20',
  'timeAvg': '8.816666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:25',
  'timeAvg': '9.016666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:30',
  'timeAvg': '8.958333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:35',
  'timeAvg': '9.266666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:40',
  'timeAvg': '9.383333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:45',
  'timeAvg': '9.291666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '06:50',
  'timeAvg': '9.466666666666667'},
 {'date': '20230110', 'carType': '소형차', 'time': '06:55', 'timeAvg': '9.6'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07  ',
  'timeAvg': '8.716666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:00',
  'timeAvg': '9.416666666666666'},
 {'date': '20230110', 'carType': '소형차', 'time': '07:05', 'timeAvg': '9.75'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:10',
  'timeAvg': '9.866666666666667'},
 {'date': '20230110', 'carType': '소형차', 'time': '07:15', 'timeAvg': '9.925'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:20',
  'timeAvg': '10.416666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:25',
  'timeAvg': '10.633333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:30',
  'timeAvg': '10.416666666666666'},
 {'date': '20230110', 'carType': '소형차', 'time': '07:35', 'timeAvg': '10.85'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:40',
  'timeAvg': '10.883333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '07:45', 'timeAvg': '10.75'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '07:50',
  'timeAvg': '11.133333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '07:55', 'timeAvg': '11.2'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08  ',
  'timeAvg': '8.666666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:00',
  'timeAvg': '10.716666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:05',
  'timeAvg': '11.083333333333334'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:10',
  'timeAvg': '11.033333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:15',
  'timeAvg': '10.641666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:20',
  'timeAvg': '10.783333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '08:25', 'timeAvg': '10.8'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:30',
  'timeAvg': '10.383333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:35',
  'timeAvg': '10.266666666666667'},
 {'date': '20230110', 'carType': '소형차', 'time': '08:40', 'timeAvg': '10.05'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:45',
  'timeAvg': '10.058333333333334'},
 {'date': '20230110', 'carType': '소형차', 'time': '08:50', 'timeAvg': '10.0'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '08:55',
  'timeAvg': '9.883333333333333'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '09  ',
  'timeAvg': '8.616666666666667'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '09:00',
  'timeAvg': '9.733333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '09:05', 'timeAvg': '9.3'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '09:10',
  'timeAvg': '9.166666666666666'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '09:15',
  'timeAvg': '9.508333333333333'},
 {'date': '20230110', 'carType': '소형차', 'time': '09:20', 'timeAvg': '9.4'},
 {'date': '20230110', 'carType': '소형차', 'time': '09:25', 'timeAvg': '9.2'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '09:30',
  'timeAvg': '9.516666666666667'},
 {'date': '20230110', 'carType': '소형차', 'time': '09:35', 'timeAvg': '9.45'},
 {'date': '20230110',
  'carType': '소형차',
  'time': '09:40',
  'timeAvg': '9.833333333333334'}]

In [10]:
import pandas as pd
df = pd.DataFrame(records)
df

        date carType   time             timeAvg
0   20230110     소형차  10:10  11.433333333333334
1   20230110     소형차  10:15  11.333333333333334
2   20230110     소형차  10:20  11.783333333333333
3   20230110     소형차  10:25  11.783333333333333
4   20230110     소형차  10:30  11.558333333333334
..       ...     ...    ...                 ...
94  20230110     소형차  09:20                 9.4
95  20230110     소형차  09:25                 9.2
96  20230110     소형차  09:30   9.516666666666667
97  20230110     소형차  09:35                9.45
98  20230110     소형차  09:40   9.833333333333334

[99 rows x 4 columns]

## XML 활용

In [11]:
import lxml
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "http://data.ex.co.kr/openapi/trtm/realUnitTrtm?key=1308370912&type=xml&iStartUnitCode=101&iEndUnitCode=103"
result = requests.get(url)
content = result.content
soup = BeautifulSoup(content, "lxml") # html.parser 
# print(soup)
print(soup.prettify())

timeAvg_lists = soup.find_all("timeavg")
stddate_lists = soup.find_all("stddate")
stdtime_lists = soup.find_all("stdtime")

avgTime = []
stddate = []
stdtime = []
for timeAvg, date, time in zip(timeAvg_lists, stddate_lists, stdtime_lists):
  print(timeAvg, date, time)
  # print(time.get_text())
  avgTime.append(timeAvg.get_text())
  stddate.append(date.get_text())
  stdtime.append(time.get_text())

df = pd.DataFrame({
    "date": stddate, 
    "time": stdtime, 
    "avgTime": avgTime
})

df

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<html>
 <body>
  <data>
   <code>
    SUCCESS
   </code>
   <message>
    인증키가 유효합니다.
   </message>
   <count>
    805
   </count>
   <numofrows>
    10
   </numofrows>
   <pageno>
    1
   </pageno>
   <pagesize>
    81
   </pagesize>
   <realunittrtmvo>
    <efcvtrfl>
     61
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:15
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.066666666666666
    </timeavg>
    <timemax>
     10.833
    </timemax>
    <timemin>
     6.150
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     13
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:20
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.166666666666666
    </timeavg>
    <timemax>
     10.833
    </timemax>
    <timemin>
     6.566
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     14
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:25
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.15
    </timeavg>
    <timemax>
     10.716
    </timemax>
    <timemin>
     6.800
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     96
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:30
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.125
    </timeavg>
    <timemax>
     9.766
    </timemax>
    <timemin>
     6.900
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     19
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:35
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.1
    </timeavg>
    <timemax>
     9.500
    </timemax>
    <timemin>
     6.900
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     31
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:40
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.183333333333334
    </timeavg>
    <timemax>
     9.766
    </timemax>
    <timemin>
     7.216
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     105
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:45
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.241666666666667
    </timeavg>
    <timemax>
     11.283
    </timemax>
    <timemin>
     7.133
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     31
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:50
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.333333333333334
    </timeavg>
    <timemax>
     10.150
    </timemax>
    <timemin>
     7.700
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     26
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     05:55
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.45
    </timeavg>
    <timemax>
     11.283
    </timemax>
    <timemin>
     7.266
    </timemin>
   </realunittrtmvo>
   <realunittrtmvo>
    <efcvtrfl>
     498
    </efcvtrfl>
    <endunitcode>
     103
    </endunitcode>
    <endunitnm>
     수원신갈
    </endunitnm>
    <startendstdtypecode>
     2
    </startendstdtypecode>
    <startendstdtypenm>
     도착기준통행시간
    </startendstdtypenm>
    <startunitcode>
     101
    </startunitcode>
    <startunitnm>
     서울
    </startunitnm>
    <stddate>
     20230110
    </stddate>
    <stdtime>
     06
    </stdtime>
    <tcscartypecode>
     1
    </tcscartypecode>
    <tcscartypedivcode>
     1
    </tcscartypedivcode>
    <tcscartypedivname>
     소형차
    </tcscartypedivname>
    <tcscartypename>
     1종
    </tcscartypename>
    <timeavg>
     8.166666666666666
    </timeavg>
    <timemax>
     14.216
    </timemax>
    <timemin>
     7.050
    </timemin>
   </realunittrtmvo>
  </data>
 </body>
</html>
<timeavg>8.066666666666666</timeavg> <stddate>20230110</stddate> <stdtime>05:15</stdtime>
<timeavg>8.166666666666666</timeavg> <stddate>20230110</stddate> <stdtime>05:20</stdtime>
<timeavg>8.15</timeavg> <stddate>20230110</stddate> <stdtime>05:25</stdtime>
<timeavg>8.125</timeavg> <stddate>20230110</stddate> <stdtime>05:30</stdtime>
<timeavg>8.1</timeavg> <stddate>20230110</stddate> <stdtime>05:35</stdtime>
<timeavg>8.183333333333334</timeavg> <stddate>20230110</stddate> <stdtime>05:40</stdtime>
<timeavg>8.241666666666667</timeavg> <stddate>20230110</stddate> <stdtime>05:45</stdtime>
<timeavg>8.333333333333334</timeavg> <stddate>20230110</stddate> <stdtime>05:50</stdtime>
<timeavg>8.45</timeavg> <stddate>20230110</stddate> <stdtime>05:55</stdtime>
<timeavg>8.166666666666666</timeavg> <stddate>20230110</stddate> <stdtime>06  </stdtime>

       date   time            avgTime
0  20230110  05:15  8.066666666666666
1  20230110  05:20  8.166666666666666
2  20230110  05:25               8.15
3  20230110  05:30              8.125
4  20230110  05:35                8.1
5  20230110  05:40  8.183333333333334
6  20230110  05:45  8.241666666666667
7  20230110  05:50  8.333333333333334
8  20230110  05:55               8.45
9  20230110   06    8.166666666666666

## 네이버 주식 데이터 수집
- 다중 페이지

In [15]:
!pip install fake_useragent

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fake_useragent
  Downloading fake_useragent-1.1.1-py3-none-any.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 KB 5.7 MB/s eta 0:00:00
Requirement already satisfied: importlib-resources>=5.0 in /usr/local/lib/python3.8/dist-packages (from fake_useragent) (5.10.1)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources>=5.0->fake_useragent) (3.11.0)
Installing collected packages: fake_useragent
Successfully installed fake_useragent-1.1.1

In [23]:
import requests
import pandas as pd 
from bs4 import BeautifulSoup
from fake_useragent import UserAgent 

company_code = '403550'
url = 'https://finance.naver.com/item/sise_day.naver?code='+company_code
# print(url)

ua = UserAgent()
custom_headers = {
    'user-agent': ua.ie
}

response = requests.get(url, headers = custom_headers)
response.status_code

soup = BeautifulSoup(response.content, "html.parser")
# print(soup)

last_page = int(soup.select_one('td.pgRR').a['href'].split('=')[-1])
# print(last_page)

df = None # 페이지별로 데이터프레임 누적 병합
count = 0 # break문 작성 위해

# print(url + "&page=2")
for page in range(1, last_page + 1):
  res = requests.get(f'{url}&page={page}', headers = custom_headers)
  # print(res)
  df = pd.concat([df, pd.read_html(res.text, encoding='euc-kr')[0]], ignore_index=True)
  # if count > 2:
  #   break
  # count += 1

df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)
df

            날짜       종가     전일비       시가       고가       저가        거래량
0   2023.01.10  19500.0   150.0  19500.0  19650.0  19200.0    53526.0
1   2023.01.09  19650.0    50.0  19600.0  19800.0  19500.0    64668.0
2   2023.01.06  19600.0   750.0  18650.0  19750.0  18650.0    91707.0
3   2023.01.05  18850.0   200.0  19200.0  19600.0  18850.0    64922.0
4   2023.01.04  19050.0     0.0  18950.0  19550.0  18550.0    62912.0
..         ...      ...     ...      ...      ...      ...        ...
92  2022.08.26  27350.0   100.0  27650.0  27800.0  27000.0   654647.0
93  2022.08.25  27250.0   200.0  27350.0  27950.0  27050.0   696401.0
94  2022.08.24  27050.0   100.0  27450.0  28050.0  26600.0  1104666.0
95  2022.08.23  26950.0   650.0  26200.0  29600.0  26150.0  5814508.0
96  2022.08.22  26300.0  1700.0  28000.0  29150.0  25550.0  4495943.0

[97 rows x 7 columns]

## 오늘 미션
- 종목코드, 상장회사명을 활용하여 오늘의 주가를 가져오는 코드를 작성하세요.

In [24]:
from bs4 import BeautifulSoup
import requests
from fake_useragent import UserAgent
from datetime import datetime
import time
import pandas as pd

def get_Code(company_code):
    url ="https://finance.naver.com/item/main.nhn?code=" + company_code
    ua = UserAgent()
    headers = { 'User-agent': ua.ie }
    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.content, "html.parser")
    return soup
 
def get_Price(company_code):
    soup = get_Code(company_code)
    no_today = soup.select_one('p.no_today')
    print(no_today)
    blind = no_today.select_one('span.blind')
    return blind.text

def create_df(company_code, company_name, prices_list):
  data = pd.DataFrame({"종목코드": company_code, 
                       "상장회사": company_name, 
                       "주가": prices_list})
  return data
 
# 증시 기업코드
company_codes = ["030200", "005930", "068270", "035720"]
company_names = ["KT", "삼성전자", "셀트리온", "카카오"]

if __name__ == '__main__':
    now = datetime.now()
    print("-" * 60)
    print(now)
    print("-" * 60)
    
    prices_list = []
    for elm in company_codes:
        nowPrice = get_Price(elm)
        prices_list.append(nowPrice)

    # print(get_prices)

    stock_data = create_df(company_codes, company_names, prices_list)
    print(stock_data)

    print("-" * 60)

------------------------------------------------------------
2023-01-10 08:14:28.472744
------------------------------------------------------------
<p class="no_today">
<em class="X">
<span class="blind">34,250</span>
<span class="no3">3</span><span class="no4">4</span><span class="shim">,</span><span class="no2">2</span><span class="no5">5</span><span class="no0">0</span>
</em>
</p>
<p class="no_today">
<em class="no_down">
<span class="blind">60,400</span>
<span class="no6">6</span><span class="no0">0</span><span class="shim">,</span><span class="no4">4</span><span class="no0">0</span><span class="no0">0</span>
</em>
</p>
<p class="no_today">
<em class="no_down">
<span class="blind">165,000</span>
<span class="no1">1</span><span class="no6">6</span><span class="no5">5</span><span class="shim">,</span><span class="no0">0</span><span class="no0">0</span><span class="no0">0</span>
</em>
</p>
<p class="no_today">
<em class="no_down">
<span class="blind">60,700</span>
<span class="no6">6</span><span class="no0">0</span><span class="shim">,</span><span class="no7">7</span><span class="no0">0</span><span class="no0">0</span>
</em>
</p>
     종목코드  상장회사       주가
0  030200    KT   34,250
1  005930  삼성전자   60,400
2  068270  셀트리온  165,000
3  035720   카카오   60,700
------------------------------------------------------------